[package]
name = "tymbolica-atom-payload"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[features]
default = ["native"]
native = ["symbolica/integer-gmp", "symbolica/float-mpfr"]
wasm = ["symbolica/wasm"]

[dependencies]
ciborium = "0.2.2"
symbolica = { version = "2.2", default-features = false }
