[package]
name = "tymbolica-inflate-plugin"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
name = "tymbolica_inflate_plugin"
crate-type = ["cdylib"]

[[bin]]
name = "tymbolica-compress"
path = "src/bin/compress.rs"

[dependencies]
miniz_oxide = "0.8.9"
wasm-minimal-protocol = "0.1"
