[package]
name = "symbolica-typst-integrate-plugin"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"
repository = "https://github.com/symbolica-dev/symbolica-typst-plugin"

[lib]
name = "symbolica_typst_integrate_plugin"
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
ciborium = "0.2.2"
getrandom = "0.3"
symbolica = { version = "3.0.0", default-features = false, features = ["wasm"] }
symbolica-integrate = { version = "2.0.1", default-features = false, features = ["compressed-step-metadata"] }
symbolica-typst-atom-payload = { path = "../atom-payload", default-features = false, features = ["wasm"] }
wasm-minimal-protocol = "0.1"
