#!/usr/bin/env python3
"""Collect license texts for the locked Wasm build, including build dependencies."""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def cargo(*args):
    return subprocess.check_output(["cargo", *args], cwd=ROOT, text=True)


def source_notice(package):
    source = package["source"]
    if source.startswith("git+"):
        repository, separator, revision = source[4:].rpartition("#")
        if not separator or not revision:
            raise RuntimeError(f"Git source has no locked revision: {source}")
        repository = repository.split("?", 1)[0].removesuffix(".git")
        notice = f"Source: {source}\nRevision: {revision}\n"
        if repository.startswith("https://github.com/"):
            notice += f"Source archive: {repository}/archive/{revision}.tar.gz\n"
        else:
            notice += f"Source repository: {repository}\n"
        return notice
    return (f"Source archive: https://crates.io/api/v1/crates/"
            f"{package['name']}/{package['version']}/download\n")


def main():
    metadata = json.loads(cargo("metadata", "--locked", "--format-version", "1"))
    tree = cargo("tree", "--locked", "--package", "symbolica-typst-plugin",
                 "--target", "wasm32-unknown-unknown", "--no-default-features",
                 "--edges", "normal,build", "--prefix", "none", "--format", "{p}")
    keys = set(re.findall(r"^(\S+) v(\S+)", tree, re.MULTILINE))
    packages = sorted((p for p in metadata["packages"]
                       if p["source"] and (p["name"], p["version"]) in keys),
                      key=lambda p: (p["name"], p["version"]))
    output = ["Third-party license texts for the locked Symbolica Typst Wasm build.\n"
              "Generated by scripts/update-licenses.py; includes build-time dependencies\n"
              "conservatively. Upstream alternative licenses are reproduced without\n"
              "claiming that every alternative applies simultaneously. See THIRD_PARTY.md.\n"]
    for package in packages:
        name = package["name"]
        directory = Path(package["manifest_path"]).parent
        files = sorted(p for p in directory.iterdir() if p.is_file()
                       and any(word in p.name.lower()
                               for word in ("license", "copying", "notice", "copyright")))
        texts = [(p.name, p.read_text()) for p in files]
        if name == "alloc-stdlib":
            texts = [("LICENSE (upstream repository)",
                      (ROOT / "docs/license-sources/alloc-stdlib-LICENSE").read_text())]
        elif name in ("astro-float-macro", "astro-float-num"):
            texts = [("LICENSE (upstream repository)",
                      (ROOT / "docs/license-sources/astro-float-LICENSE").read_text())]
        elif name.startswith("malachite-"):
            texts = [(p.name, p.read_text()) for p in
                     sorted((ROOT / "docs/license-sources").glob("malachite-COPYING*"))]
            # The crate archives omit license files but retain notices in source.
            source = (directory / "src/lib.rs").read_text()
            notice = source.split("\n\n", 1)[0]
            texts.insert(0, ("Source notice", notice))
        elif name == "smartstring":
            texts = [("README license notice", (directory / "README.md").read_text()
                      .split("## Licence\n", 1)[1].split("## Code of Conduct", 1)[0]),
                     ("Mozilla Public License 2.0",
                      (ROOT / "docs/license-sources/MPL-2.0.txt").read_text())]
        if not texts:
            raise RuntimeError(f"Missing license text: {name} {package['version']}")
        output.append("\n" + "=" * 72 + f"\n{name} {package['version']}\n"
                      + f"License: {package.get('license') or package.get('license_file')}\n"
                      + f"Repository: {package.get('repository') or ''}\n"
                      + source_notice(package))
        for title, text in texts:
            output.append(f"\n--- {title} ---\n{text.rstrip()}\n")
    combined = "".join(output)
    (ROOT / "THIRD_PARTY_LICENSES.txt").write_text(
        "\n".join(line.rstrip() for line in combined.splitlines()) + "\n")
    print(f"Collected license texts for {len(packages)} dependencies")


if __name__ == "__main__":
    main()
